# Useful commands:
# docker-compose build
# docker-compose up
# docker-compose ps
# docker-compose down

version: '3.7'

services:

  backend:
    build:
      context: ./music-service
      dockerfile: Dockerfile
    depends_on:
    - postgres
    ports:
    - "8081:8081"