# Useful commands:
# docker-compose build
# docker-compose up
# docker-compose ps
# docker-compose down

version: '3.7'

services:

  testapp:
    build:
      context: ./music-service
      dockerfile: Dockerfile
    ports:
    - "8081:8081"

