# Useful commands:
# docker-compose build
# docker-compose up
# docker-compose ps
# docker-compose down



version: '3.7'
  postgres:
    image: "postgres:10"
services:
    build:
      context: ./music-service
      dockerfile: Dockerfile
    depends_on:
    - postgres
    ports:
    - "8081:8081"